routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/question');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function() {
    Route::resource('/question', 'QuestionController');
    Route::get('/profile', 'ProfileController@index')->name('profile.index');
    Route::get('/profile/comment', 'ProfileCommentController@index')->name('profile.comment.index');
    Route::post('comment/{comment}/comment', 'CommentCommentController@store')->name('comment.comment.store');
    Route::post('question/{question}/comment', 'QuestionCommentController@store')->name('question.comment.store');
    Route::post('comment/{comment}/vote', 'CommentVoteController@store')->name('comment.vote.store');
    Route::post('question/{question}/vote', 'QuestionVoteController@store')->name('question.vote.store');
});

app/Question.php
<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'body',
        'correct_comment_id',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'correct_comment_id' => 'integer',
    ];

    /**
     * Questions belong to User.
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Question has correct Comment.
     */
    public function correctComment()
    {
        return $this->belongsTo(Comment::class);
    }

    /**
     * Question has many Tags
     */
    public function tag() {
        return $this->belongsToMany(Tag::class, 'tag_questions', 'question_id', 'tag_id')->withTimestamps();
    }

    /**
     * Comments has many Comment (using polymorphism).
     */
    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }
    
    /**
     * Comments has many Votes (using polymorphism).
     */
    public function votes()
    {
        return $this->morphMany(Vote::class, 'votable');
    }
    
    /**
     * Comments has many UpVotes (using polymorphism).
     */
    public function upVotes()
    {
        return $this->morphMany(Vote::class, 'votable')->where('poin', 1);
    }

    /**
     * Comments has many downVotes (using polymorphism).
     */
    public function downVotes()
    {
        return $this->morphMany(Vote::class, 'votable')->where('poin', -1);
    }

    /**
     * Comments has many reputation (using polymorphism).
     */
    public function reputation()
    {
        return $this->morphMany(Reputation::class, 'reputable');
    }

    /**
     * Comments has total reputation.
     * 
     * @return integer
     */
    public function totalReputation()
    {
        return $this->morphMany(Reputation::class, 'reputable')->sum('poin');
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use Str;
use Auth;
use App\Tag;
use App\Question;
use Illuminate\Http\Request;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $questions = Question::with('user')
            ->withCount('comments')
            ->latest()
            ->simplePaginate();

        return view('question.index', [
            'questions' => $questions
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('question.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {        
        $user_id = Auth::user()->id;

        $tags = explode(",", $request->tag);
        foreach($tags as $tag) {
            $tag_created    = Tag::firstOrCreate([
                                    "name" => trim($tag),
                                    "slug" => Str::slug($tag)
                              ]);
            $tag_id[]       = $tag_created->id;
        }

        $question = new Question;
        $question->user_id  = $user_id;
        $question->title    = $request->title;
        $question->body     = $request->body;
        $question->save();

        $question->tag()->sync($tag_id);

        return redirect()->route('question.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        $question->load('comments.comments');
        
        return view('question.show', [
            'question' => $question
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        $question->load('tag');

        foreach($question->tag as $tag){
            $tags[] = $tag->name;
        }

        return view('question.edit', [
            'question' => $question,
            'tag'     => implode(',', $tags)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question)
    {
        $tags               = explode(",", $request->tag);
        
        foreach($tags as $tag) {
            $tag_created    = Tag::firstOrCreate([
                                "name" => trim($tag),
                                "slug" => Str::slug($tag)
                              ]);
            $tag_id[] = $tag_created->id;             
        }

        $question->title    = $request->title;
        $question->body     = $request->body;
        $question->save();
        
        $question->tag()->sync($tag_id);

        return redirect()->route('question.show', $question);
    }
}

resources/views/question/create.blade.php
@extends('layouts.master')

@section('header')
    <header class="py-10">
        <div class="max-w-4xl px-4 mx-auto sm:px-6 lg:px-8">
            <div class="lg:flex lg:items-center lg:justify-between">
                <div class="flex-1 min-w-0">
                    <h2 class="text-2xl font-bold leading-7 text-white sm:text-3xl sm:leading-9 sm:truncate">
                        Create new Questions
                    </h2>
                </div>
            </div>
        </div>
    </header>
@endsection

@section('content')
    <div class="max-w-4xl px-4 pb-12 mx-auto sm:px-6 lg:px-8">
        <div class="overflow-hidden bg-white rounded-md shadow">
            <div class="px-4 bg-white border-b border-gray-200 sm:px-6">
                <div class="pt-3 pb-4 sm:p-0">
                    <form class="w-full px-6 py-12" method="POST" action="{{ route('question.store') }}">
                        @csrf
                        @include('question.form')
                        <div class="flex flex-wrap items-center mt-4">
                            <button type="submit" class="px-4 py-2 font-bold text-gray-100 bg-blue-500 rounded hover:bg-blue-700 focus:outline-none focus:shadow-outline">
                                Save
                            </button>
                        </div>                        
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/question/edit.blade.php
@extends('layouts.master')

@section('header')
    <header class="py-10">
        <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="lg:flex lg:items-center lg:justify-between">
                <div class="flex-1 min-w-0">
                    <h2 class="text-2xl font-bold leading-7 text-white sm:text-3xl sm:leading-9 sm:truncate">
                        Edit Questions
                    </h2>
                </div>
            </div>
        </div>
    </header>
@endsection

@section('content')
    <div class="max-w-4xl mx-auto px-4 pb-12 sm:px-6 lg:px-8">
        <div class="bg-white shadow overflow-hidden rounded-md">
            <div class="bg-white px-4 border-b border-gray-200 sm:px-6">
                <div class="pt-3 pb-4 sm:p-0">
                    <form class="w-full px-6 py-12" method="POST" action="{{ route('question.update', $question) }}">
                        @csrf
                        @method('PUT')
                        @include('question.form')
                        
                        <div class="flex flex-wrap items-center mt-4">
                            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-gray-100 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                                Save
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/question/form.blade.php
<div class="flex flex-wrap mb-3">
    <label for="title" class="block mb-2 text-sm font-bold text-gray-700">
        Question Title
    </label>

    <input id="title" type="text" class="form-input w-full @error('title') border-red-500 @enderror" name="title" value="{{ old('title', $question->title ?? '') }}" autocomplete="title" autofocus>

    @error('title')
        <p class="mt-4 text-xs italic text-red-500">
            {{ $message }}
        </p>
    @enderror
</div>

<div class="flex flex-wrap mb-3">
    <label for="body" class="block mb-2 text-sm font-bold text-gray-700">
        Description
    </label>

    <textarea id="body" class="form-input w-full @error('body') border-red-500 @enderror" name="body" rows="10">{{ old('body', $question->body ?? '') }}</textarea>

    @error('password')
        <p class="mt-4 text-xs italic text-red-500">
            {{ $message }}
        </p>
    @enderror
</div>

<div class="flex flex-wrap mb-3">
    <label for="title" class="block mb-2 text-sm font-bold text-gray-700">
        Tag
    </label>
    
    <input id="tag" type="text" class="form-input w-full @error('tag') border-red-500 @enderror" name="tag" autocomplete="tag" value="{{ old('tag', $tag ?? '')  }}" autofocus>

    @error('tag')
        <p class="mt-4 text-xs italic text-red-500">
            {{ $message }}
        </p>
    @enderror
</div>

@push('scripts')
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script>tinymce.init({selector:'#body'});</script>
@endpush

resources/views/question/index.blade.php
@extends('layouts.master')

@section('header')
    <header class="py-10">
        <div class="max-w-4xl px-4 mx-auto sm:px-6 lg:px-8">
            <div class="lg:flex lg:items-center lg:justify-between">
                <div class="flex-1 min-w-0">
                    <h2 class="text-2xl font-bold leading-7 text-white sm:text-3xl sm:leading-9 sm:truncate">
                        All Questions
                    </h2>
                </div>
                <div class="flex mt-5 lg:mt-0 lg:ml-4">
                    <span class="rounded-md shadow-sm sm:ml-3">
                        <a href="{{ route('question.create') }}" class="inline-flex items-center px-4 py-2 text-sm font-medium leading-5 text-white transition duration-150 ease-in-out bg-indigo-500 border border-transparent rounded-md hover:bg-indigo-400 focus:outline-none focus:shadow-outline-indigo focus:border-indigo-600">
                            <svg class="w-5 h-5 mr-2 -ml-1" fill="currentColor" viewBox="0 0 24 24">
                                <path class="heroicon-ui" d="M17 11a1 1 0 0 1 0 2h-4v4a1 1 0 0 1-2 0v-4H7a1 1 0 0 1 0-2h4V7a1 1 0 0 1 2 0v4h4z"/>
                            </svg>
                            Create new Questions
                        </a>
                    </span>
                </div>
            </div>
        </div>
    </header>
@endsection

@section('content')
    <div class="max-w-4xl px-4 pb-12 mx-auto sm:px-6 lg:px-8">
        <div class="overflow-hidden bg-white rounded-md shadow">
            <div class="px-4 pt-5 bg-white border-b border-gray-200 sm:px-6">
                <h3 class="text-lg font-medium leading-6 text-gray-900">
                    Candidates
                </h3>
                <div class="pt-3 pb-4 sm:p-0">
                    <div class="sm:hidden">
                        <select class="block w-full text-gray-900 transition duration-150 ease-in-out border-gray-300 form-select focus:outline-none focus:shadow-outline-blue focus:border-blue-300">
                            <option>Applied</option>
                            <option>Phone screening</option>
                            <option selected>Interview</option>
                            <option>Offer</option>
                            <option>Hired</option>
                        </select>
                    </div>
                    <div class="hidden sm:block">
                        <div>
                            <nav class="flex -mb-px">
                                <a href="#" class="px-1 py-4 text-sm font-medium leading-5 text-gray-500 whitespace-no-wrap transition duration-150 ease-in-out border-b-2 border-transparent hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300">
                                    Applied
                                </a>
                                <a href="#" class="px-1 py-4 ml-8 text-sm font-medium leading-5 text-gray-500 whitespace-no-wrap transition duration-150 ease-in-out border-b-2 border-transparent hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300">
                                    Phone screening
                                </a>
                                <a href="#" class="px-1 py-4 ml-8 text-sm font-medium leading-5 text-indigo-600 whitespace-no-wrap transition duration-150 ease-in-out border-b-2 border-indigo-500 focus:outline-none focus:text-indigo-800 focus:border-indigo-700">
                                    Interview
                                </a>
                                <a href="#" class="px-1 py-4 ml-8 text-sm font-medium leading-5 text-gray-500 whitespace-no-wrap transition duration-150 ease-in-out border-b-2 border-transparent hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300">
                                    Offer
                                </a>
                                <a href="#" class="px-1 py-4 ml-8 text-sm font-medium leading-5 text-gray-500 whitespace-no-wrap transition duration-150 ease-in-out border-b-2 border-transparent hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300">
                                    Hired
                                </a>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <div class="px-4 pt-5 pb-3 sm:px-6">
                <div>
                    <label for="filter" class="sr-only">Search candidates</label>
                    <div class="flex rounded-md shadow-sm">
                        <div class="relative flex-grow focus-within:z-10">
                            <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                <svg class="w-5 h-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                                    <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
                                </svg>
                            </div>
                            <input id="filter" class="block w-full py-2 pl-10 pr-3 text-gray-900 placeholder-gray-400 transition duration-150 ease-in-out border border-gray-300 rounded-none appearance-none rounded-l-md focus:outline-none focus:shadow-outline-blue focus:border-blue-300 sm:text-sm sm:leading-5" placeholder="John Doe" />
                        </div>
                        <button class="relative flex items-center px-3 py-2 -ml-px text-sm leading-5 text-gray-900 transition duration-150 ease-in-out border border-gray-300 rounded-r-md bg-gray-50 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 focus:z-10">
                            <svg class="w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd" d="M3 3a1 1 0 011-1h12a1 1 0 011 1v3a1 1 0 01-.293.707L12 11.414V15a1 1 0 01-.293.707l-2 2A1 1 0 018 17v-5.586L3.293 6.707A1 1 0 013 6V3z" clip-rule="evenodd" />
                            </svg>
                            <span class="ml-2">Filter</span>
                        </button>
                    </div>
                </div>
            </div>
            <ul>
                @foreach ($questions as $question)           
                    <li>
                        <a href="{{ route('question.show', $question) }}" class="block transition duration-150 ease-in-out hover:bg-gray-50 focus:outline-none focus:bg-gray-50">
                            <div class="flex items-center px-4 py-4 sm:px-6">
                                <div class="flex items-start flex-1 min-w-0">
                                    <div class="flex-shrink-0">                                        
                                        <img class="w-12 h-12 rounded-full" src="https://i.pravatar.cc/150?img={{ $question->user_id }}" alt="">
                                    </div>
                                    <div class="flex-1 min-w-0 px-4 md:grid md:grid-cols-2 md:gap-4">
                                        <div>
                                            <div class="font-medium font-semibold leading-5 truncate">{{ $question->title }}</div>
                                            <div class="flex items-center mt-2 text-sm leading-5 text-gray-500">
                                                by : <span class="ml-1 text-sm text-indigo-600 "> {{ $question->user->name }}</span>
                                            </div>
                                            <div class="flex my-2 -ml-1">
                                                @foreach ($question->tag as $tag)
                                                    <span class="px-2 ml-1 text-xs text-blue-800 bg-blue-200 rounded-full">{{ $tag->name }}</span>
                                                @endforeach
                                            </div>
                                        </div>
                                        <div class="hidden md:block">
                                            <div>
                                                <div class="text-sm leading-5 text-gray-900">
                                                    Created at
                                                    <time datetime="2020-01-07">{{ $question->created_at->diffForHumans() }}</time>
                                                </div>
                                               <div class="flex items-center">
                                                    @if ($question->correct_comment_id)
                                                        <div class="flex items-center mt-2 text-sm leading-5 text-gray-500">
                                                            <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-green-400" fill="currentColor" viewBox="0 0 20 20">
                                                                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                                                            </svg>
                                                            Completed 
                                                        </div>
                                                        <span class="mx-2 text-4xl leading-3 text-gray-400 text-bold">&middot;</span>
                                                    @endif
                                                    <div class="flex items-center mt-2 text-sm leading-5 text-gray-500">
                                                        <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-green-400" fill="currentColor" viewBox="0 0 24 24">
                                                            <path class="heroicon-ui" d="M2 15V5c0-1.1.9-2 2-2h16a2 2 0 0 1 2 2v15a1 1 0 0 1-1.7.7L16.58 17H4a2 2 0 0 1-2-2zM20 5H4v10h13a1 1 0 0 1 .7.3l2.3 2.29V5z" />
                                                        </svg>
                                                        {{ $question->comments_count }} {{ Str::plural('comment', $question->comments_count) }}
                                                    </div>
                                               </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div>
                                    <svg class="w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                                        <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                                    </svg>
                                </div>
                            </div>
                        </a>
                    </li>
                @endforeach
            </ul>
            <div class="flex items-center justify-between px-4 py-3 bg-white border-t border-gray-200 sm:px-6">
                <div class="hidden sm:block">
                    <p class="text-sm leading-5 text-gray-700">
                        Total 
                        <span class="font-medium">{{ $question->count() }}</span>
                        results
                    </p>
                </div>
                <div class="flex justify-between flex-1 sm:justify-end">
                    {{ $questions->links('vendor.pagination.simple-default') }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/question/show.blade.php
@extends('layouts.master')

@section('header')
    <header class="py-10">
        <div class="max-w-4xl px-4 mx-auto sm:px-6 lg:px-8">
            <div class="lg:flex lg:items-center lg:justify-between">
                <div class="flex-1 min-w-0">
                    <h2 class="text-2xl font-bold leading-7 text-white sm:text-3xl sm:leading-9 sm:truncate">
                        {{ $question->title }}
                    </h2>
                </div>
                <a href="{{ route('question.edit', $question) }}" class="flex items-center px-4 py-1 text-sm text-white bg-blue-700 rounded-full">
                    <svg class="w-4 h-4 mr-1 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                        <path class="heroicon-ui" d="M6.3 12.3l10-10a1 1 0 0 1 1.4 0l4 4a1 1 0 0 1 0 1.4l-10 10a1 1 0 0 1-.7.3H7a1 1 0 0 1-1-1v-4a1 1 0 0 1 .3-.7zM8 16h2.59l9-9L17 4.41l-9 9V16zm10-2a1 1 0 0 1 2 0v6a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6c0-1.1.9-2 2-2h6a1 1 0 0 1 0 2H4v14h14v-6z" />
                    </svg>
                    Edit
                </a>
            </div>
        </div>
    </header>
@endsection

@section('content')
    <div class="max-w-4xl px-4 pb-12 mx-auto sm:px-6 lg:px-8">
        <div class="overflow-hidden bg-white rounded-md shadow">
            <div class="px-8 py-10 bg-white border-gray-200" x-data="{ showForm : false }">
                <div class="flex items-start justify-between">
                    <div class="flex items-start">
                        <div class="w-12 h-12 mr-2">
                            <img class="w-12 h-12 rounded-full" src="https://i.pravatar.cc/150?img={{ $question->user_id }}" alt="">
                        </div>
                        <a href="#" class="ml-2 text-xl font-semibold text-indigo-500">{{ $question->user->name }}</a>
                    </div>
                    <div class="flex items-center justify-center w-8 h-8 mr-4 text-sm font-semibold text-green-700 bg-green-100 rounded-full">{{ $question->totalReputation() }}</div>
                </div>
                <div class="ml-16 mr-4">{!! $question->body !!}</div>
                <div class="flex items-center justify-between mt-3 ml-16 text-sm text-gray-400">
                    <div class="flex items-center">
                        <button class="hover:text-blue-500 hover:underline" x-on:click="showForm = !showForm">Reply</button>
                        <span class="mx-2 text-4xl leading-3 text-bold">&middot;</span>
                        @include('components.upvotes', ['model' => $question])
                        <span class="mx-2 text-4xl leading-3 text-bold">&middot;</span>
                        @include('components.downvotes', ['model' => $question])
                    </div>
                    <div class="flex items-baseline mr-4">
                        <div class="flex items-baseline">
                            @foreach ($question->tag as $tag)
                                <span class="px-2 ml-1 text-xs text-blue-800 bg-blue-200 rounded-full">{{ $tag->name }}</span>
                            @endforeach
                        </div>
                        <span class="ml-4">{{ $question->created_at->diffForHumans() }}</span>
                    </div>
                </div>
                <div class="ml-16">
                    @include('components.comment-form', ['model' => $question])
                </div>
            </div>
        </div>
        <div>
            @foreach ($question->comments as $comment)
                <div class="my-2 overflow-hidden bg-white rounded-md shadow">
                    <div class="flex p-4 mb-2 bg-white border-gray-200 sm:p-6">
                        <img class="w-12 h-12 rounded-full" src="https://i.pravatar.cc/150?img={{ $comment->user_id }}" alt="">
                        <div class="w-full ml-6" x-data="{ showForm : false}">
                            <div class="flex items-center justify-between">
                                <div class="flex items-center justify-between">
                                    <a href="#" class="text-blue-500">{{ $comment->user->name }}</a>
                                </div>
                                <div class="flex items-center justify-center w-8 h-8 mt-2 mr-8 text-sm font-semibold text-green-700 bg-green-100 rounded-full">{{ $comment->totalReputation() }}</div>    
                            </div>
                            <p class="mt-1 text-sm">{!! $comment->body !!}</p>
                            <div class="flex items-center justify-between mt-1 mr-6 text-sm text-gray-400">
                                <div class="flex items-center">
                                    <button class=" hover:text-blue-500 hover:underline"  x-on:click="showForm = !showForm">Reply</button>
                                    <span class="mx-2 text-4xl leading-3 text-bold">&middot;</span>
                                    @include('components.upvotes', ['model' => $comment])
                                    <span class="mx-2 text-4xl leading-3 text-bold">&middot;</span>
                                    @include('components.downvotes', ['model' => $comment])
                                </div>
                                <div>
                                    {{ $comment->created_at->diffForHumans() }}
                                </div>
                            </div>
                            @include('components.comment-form', ['model' => $comment])

                            <div>
                                @foreach ($comment->comments as $subComment)
                                    <div class="relative flex mt-4">
                                        <img class="w-12 h-12 rounded-full" src="https://i.pravatar.cc/150?img={{ $subComment->user_id }}" alt="">
                                        <div class="w-full ml-3 mr-6">
                                            <div class="flex items-center justify-between">
                                                <a href="#" class="text-blue-500">{{ $subComment->user->name }}</a>
                                                <div class="flex items-center justify-center w-8 h-8 mt-2 mr-2 text-sm font-semibold text-green-700 bg-green-100 rounded-full">{{ $subComment->totalReputation() }}</div>
                                            </div>
                                            <p class="mt-1 text-sm">{!! $subComment->body !!}</p>
                                            <div class="flex items-center justify-between mt-1 text-sm text-gray-400">
                                                <div class="flex items-center">
                                                    @include('components.upvotes', ['model' => $subComment])
                                                    <span class="mx-2 text-4xl leading-3 text-bold">&middot;</span>
                                                    @include('components.downvotes', ['model' => $subComment])
                                                </div>
                                                <div>
                                                    {{ $subComment->created_at->diffForHumans() }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection


@push('scripts')
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script>tinymce.init({selector:'.body'});</script>
@endpush